apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hellowrlds.hlw.io
spec:
  group: hlw.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
  scope: Namespaced
  names:
    plural: hellowrlds
    singular: hellowrld
    kind: HelloWorld
    shortNames:
      - hlwlrd
